In [1]:
from pyplasm import*
DISTR([[1,2,3,4], 3])

Evaluating fenvs.py..
...fenvs.py imported in 0.00910598186561 seconds


[[1, 3], [2, 3], [3, 3], [4, 3]]

In [2]:
import numpy as np
a = ([1,2,3], [3,4,5], [6,7,8])
np.array(a)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.transpose(np.array(a))   ## come TRANS delle slide Pyplasm

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 8]])

In [4]:
(np.transpose(np.array(a))).tolist()

[[1, 3, 6], [2, 4, 7], [3, 5, 8]]

In [5]:
3*np.array([1,2,3])

array([3, 6, 9])

In [6]:
A = [ [1,2,3], [4,5,6], [7,8,9] ]
B = [ [10,20,30], [40,50,60], [70,80,90] ]


In [7]:
TRANS([A,B])

[[[1, 2, 3], [10, 20, 30]],
 [[4, 5, 6], [40, 50, 60]],
 [[7, 8, 9], [70, 80, 90]]]

In [9]:
AA(TRANS)(TRANS([A,B]))

[[[1, 10], [2, 20], [3, 30]],
 [[4, 40], [5, 50], [6, 60]],
 [[7, 70], [8, 80], [9, 90]]]

In [10]:
AA(AA(SUM))(AA(TRANS)(TRANS([A,B])))     ## MATSUM

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [11]:
def MATSUM(args):
     return AA(AA(SUM)) (AA(TRANS)(TRANS(args)))

In [14]:
MATSUM([A,B])

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [15]:
from pyplasm import*
A = [ [1,2,3], [4,5,6], [7,8,9] ]
B = [ [10,20,30], [40,50,60], [70,80,90] ]
[A,TRANS(B)]

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]]

In [17]:
DISTR([A,TRANS(B)])     ## righe della prima accoppiate alle colonne della seconda

[[[1, 2, 3], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]],
 [[4, 5, 6], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]],
 [[7, 8, 9], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]]]

In [18]:
(AA(DISTL)(DISTR([A,TRANS(B)])))   ## prima riga prima colonna, prima riga seconda colonna...

[[[[1, 2, 3], [10, 40, 70]],
  [[1, 2, 3], [20, 50, 80]],
  [[1, 2, 3], [30, 60, 90]]],
 [[[4, 5, 6], [10, 40, 70]],
  [[4, 5, 6], [20, 50, 80]],
  [[4, 5, 6], [30, 60, 90]]],
 [[[7, 8, 9], [10, 40, 70]],
  [[7, 8, 9], [20, 50, 80]],
  [[7, 8, 9], [30, 60, 90]]]]

In [19]:
AA(AA(INNERPROD))(AA(DISTL)(DISTR ([A, TRANS (B)])))  ## due volte AA perchè devo penetrare 2 parentesi quadre

[[300, 360, 420], [660, 810, 960], [1020, 1260, 1500]]

In [21]:
## PRODOTTO TRA MATRICI CON NUMPY
from numpy import*
array(A)*array(B)

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [23]:
## Generazione punti random nel piano

from random import random
def randomPoints(m, sx=1, sy=1):
    def point():
        return [random() * sx, random() * sy]
    return [point() for k in range(m)]
verts = randomPoints(200, 2*PI, 2)
obj = MKPOL([verts, AA(LIST)(range(200)), None])
VIEW(obj)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000C091900> >

In [ ]:
def x (p):
    u,v = p
    return v * COS(u)
def y (p):
    u,v = p
    return v * SIN(u)
obj = MAP([ x,y ])(obj)    ## obj era l'insieme di punti di prima, MAP prende una lista di coordinate e un dominio 
VIEW(obj)                  ## e applica ai vertici di questo dominio le funzioni nell'argomento